import type { Argv } from "yargs"
import path from "path"
import fs from "fs/promises"
import { cmd } from "./cmd"

const AGENT_TEMPLATES: Record<string, string> = {
  architect: `---
name: architect
description: Software architecture specialist for system design, scalability, and technical decision-making
tools:
  Read: true
  Grep: true
  Glob: true
hidden: true
---

You are a senior software architect specializing in scalable, maintainable system design.

## Your Role

- Design system architecture for new features
- Evaluate technical trade-offs
- Recommend patterns and best practices
- Identify scalability bottlenecks
- Ensure consistency across codebase

## Architecture Review Process

1. **Current State Analysis** — Review existing architecture, identify patterns, document tech debt
2. **Requirements Gathering** — Functional and non-functional requirements, integration points
3. **Design Proposals** — Multiple options with trade-off analysis
4. **Recommendation** — Clear recommendation with rationale
`,
  planner: `---
name: planner
description: Expert planning specialist for complex features and refactoring
tools:
  Read: true
  Grep: true
  Glob: true
hidden: true
---

You are an expert planning specialist focused on creating comprehensive, actionable implementation plans.

## Your Role

- Analyze requirements and create detailed implementation plans
- Break down complex features into manageable steps
- Identify dependencies and potential risks
- Suggest optimal implementation order

## Planning Process

1. **Requirements Analysis** — Understand the request, ask clarifying questions, identify success criteria
2. **Architecture Review** — Analyze codebase structure, identify affected components
3. **Task Breakdown** — Ordered list of tasks with dependencies and estimates
4. **Risk Assessment** — Identify potential issues and mitigation strategies
`,
  "code-reviewer": `---
name: code-reviewer
description: Expert code review specialist for quality, security, and maintainability
tools:
  Read: true
  Grep: true
  Glob: true
hidden: true
---

You are an expert code reviewer that analyzes code for best practices, security issues, and maintainability.

## Review Checklist

- **Correctness** — Logic errors, edge cases, race conditions
- **Security** — Injection, auth issues, secrets, input validation
- **Performance** — N+1 queries, unnecessary allocations, missing indexes
- **Readability** — Naming, complexity, dead code, documentation
- **Testing** — Coverage gaps, missing edge case tests

## Output Format

For each finding:
- Severity: Critical / Warning / Info
- File and line number
- Description of issue
- Suggested fix
`,
  "security-reviewer": `---
name: security-reviewer
description: Security vulnerability detection and remediation specialist
tools:
  Read: true
  Grep: true
  Glob: true
hidden: true
---

You are a security specialist focused on finding and fixing vulnerabilities.

## Security Checklist

- SQL injection / NoSQL injection
- XSS (stored, reflected, DOM-based)
- CSRF protection
- Authentication/Authorization bypass
- Secrets in code (API keys, passwords, tokens)
- Insecure deserialization
- SSRF vulnerabilities
- Rate limiting
- Input validation
- Error message information leakage
`,
  "tdd-guide": `---
name: tdd-guide
description: Test-Driven Development specialist enforcing write-tests-first methodology
tools:
  Read: true
  Write: true
  Edit: true
  Bash: true
  Grep: true
hidden: true
---

You are a TDD specialist that enforces test-driven development practices.

## TDD Workflow

1. **RED** — Write a failing test first
2. **GREEN** — Write minimal code to pass the test
3. **REFACTOR** — Improve code while keeping tests green

## Rules

- Always write tests before implementation
- Aim for 80%+ code coverage
- Test edge cases and error scenarios
- Use descriptive test names
- Keep tests independent
`,
}

const CONFIG_TEMPLATE = `{
  "$schema": "https://mtycoder.example.com/config.json",

  // AI provider configuration
  // Run 'mty providers' or use /connect in TUI to set up
  "provider": {},

  // Expert sub-agents (loaded from .mtycoder/agents/)
  // Available via @agent-name in prompts or Tab to switch
  "agent": {},

  // Permission rules for tools
  "permission": {},

  // MCP (Model Context Protocol) servers
  "mcp": {
    "context7": {
      "type": "local",
      "command": ["npx", "-y", "@upstash/context7-mcp@latest"]
    }
  },

  // Skill configuration
  "skills": {
    "paths": []
  }
}
`

const AGENTS_TEMPLATE = `# Project Instructions for MtyCoder

> Auto-generated by \`mty init\`. Edit this file to guide AI sessions.

## Build & Test

\`\`\`bash
# Add your build/test/lint commands here
\`\`\`

## Architecture

<!-- Describe key directories and their purposes -->

## Conventions

<!-- Any project-specific conventions the AI should know -->

---

## Code Quality Standards

### Immutability
- Create new objects, never mutate existing ones
- Use spread operator for immutable updates

### File Organization
- 200-400 lines typical, 800 max per file
- Organize by feature/domain, not by type
- High cohesion, low coupling

### Error Handling
- Handle errors explicitly at every level
- Provide user-friendly error messages in UI-facing code
- Log detailed error context on the server side
- Never silently swallow errors

### Input Validation
- Validate all user input at system boundaries
- Use schema-based validation where available (Zod, etc.)
- Fail fast with clear error messages
- Never trust external data

### Security Checklist (Before Every Commit)
- [ ] No hardcoded secrets (API keys, passwords, tokens)
- [ ] All user inputs validated
- [ ] SQL injection prevention (parameterized queries)
- [ ] XSS prevention (sanitized HTML)
- [ ] Rate limiting on endpoints
- [ ] Error messages don't leak sensitive data

### Testing Requirements (Target: 80%+ Coverage)
- **Unit Tests** — Individual functions, utilities, components
- **Integration Tests** — API endpoints, database operations
- **E2E Tests** — Critical user flows
- Write tests BEFORE implementation (TDD: RED → GREEN → REFACTOR)
`

export const InitCommand = cmd({
  command: "init",
  describe: "initialize .mtycoder project configuration",
  builder(yargs) {
    return yargs
      .option("force", {
        alias: "f",
        type: "boolean",
        describe: "overwrite existing config",
        default: false,
      })
      .option("agents", {
        type: "boolean",
        describe: "also create AGENTS.md template",
        default: true,
      })
  },
  async handler(args) {
    const cwd = process.cwd()
    const configDir = path.join(cwd, ".mtycoder")
    const configFile = path.join(configDir, "mtycoder.jsonc")
    const agentsDir = path.join(configDir, "agents")
    const agentsFile = path.join(cwd, "AGENTS.md")

    // Check if .mtycoder already exists
    try {
      await fs.access(configDir)
      if (!args.force) {
        console.log(`.mtycoder/ already exists in ${cwd}`)
        console.log("Use --force to overwrite")
        return
      }
    } catch {
      // Directory doesn't exist, good
    }

    // Create .mtycoder directory structure
    await fs.mkdir(configDir, { recursive: true })
    await fs.mkdir(path.join(configDir, "skills"), { recursive: true })
    await fs.mkdir(agentsDir, { recursive: true })

    // Write mtycoder.jsonc
    await fs.writeFile(configFile, CONFIG_TEMPLATE, "utf-8")
    console.log(`Created ${configFile}`)

    // Write agent templates
    for (const [name, content] of Object.entries(AGENT_TEMPLATES)) {
      const agentFile = path.join(agentsDir, `${name}.md`)
      await fs.writeFile(agentFile, content, "utf-8")
      console.log(`Created agents/${name}.md`)
    }

    // Write AGENTS.md if requested
    if (args.agents) {
      try {
        await fs.access(agentsFile)
        if (!args.force) {
          console.log(`AGENTS.md already exists, skipping (use --force to overwrite)`)
        } else {
          await fs.writeFile(agentsFile, AGENTS_TEMPLATE, "utf-8")
          console.log(`Created ${agentsFile}`)
        }
      } catch {
        await fs.writeFile(agentsFile, AGENTS_TEMPLATE, "utf-8")
        console.log(`Created ${agentsFile}`)
      }
    }

    console.log("")
    console.log("Project initialized! Next steps:")
    console.log("  1. Run 'mty' to start the TUI")
    console.log("  2. Use /connect to set up an AI provider")
    console.log("  3. Edit .mtycoder/mtycoder.jsonc to customize settings")
    console.log("  4. Edit AGENTS.md to add project-specific instructions")
    console.log("")
    console.log("Built-in agents: architect, planner, code-reviewer, security-reviewer, tdd-guide")
    console.log("Built-in MCP: context7 (real-time library docs)")
    console.log("Built-in skills: code-review, tdd, security-review, search-first, and 20+ more")
  },
})
